- hosts: all
  vars_prompt:
  - name: dvd_dir
    prompt: "Enter the DVD Mount Point"
    private: no

  tasks:
  - file:
      state: directory
      path: "{{ dvd_dir }}"

  - mount:
      src: "/dev/cdrom"
      path: "{{ dvd_dir }}"
      state: mounted
      fstype: "iso9660"

  - yum_repository:
      baseurl: "{{ dvd_dir }}/AppStream"
      name: "dvd1"
      description: "ansible dvd1"
      gpgcheck: no

  - yum_repository:
      baseurl: "{{ dvd_dir }}/BaseOS"
      name: "dvd2"
      description: "ansible dvd2"
      gpgcheck: no

  - name: Install HTTPD
    package:
      name: "httpd"
      state: present

  - name: permit traffic in default zone on port 8080/tcp
    firewalld:
      port: "8080/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - copy:
      dest: "/etc/httpd/conf.d/webserver.conf"
      src: "webserver.conf"

  - copy:
      dest: "/var/www/html/index.html"
      src: "index.html"
    notify: server

  handlers:
  - name: server
    service:
      name: "httpd"
      state: restarted
      enabled: yes

  

